export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const SET_BANNER = "SET_BANNER";
export const GET_LIST_THEATER = "GET_LIST_THEATER";
export const GET_CHI_TIET_PHIM = "GET_CHI_TIET_PHIM";
export const DANG_NHAP = "DANG_NHAP";
export const SET_THONG_TIN_USER = "SET_THONG_TIN_USER";
export const SET_CHI_TIET_PHONG_VE = "SET_CHI_TIET_PHONG_VE";
export const DAT_VE = "DAT_VE";
export const DAT_VE_DONE = "DAT_VE_DONE";
export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const LAY_THONG_TIN_USER = "LAY_THONG_TIN_USER";

export const GET_DANH_SACH_PHIM_KEYWORD = "GET_DANH_SACH_PHIM_KEYWORD";

export const SET_THONG_TIN_PHIM = "SET_THONG_TIN_PHIM";

export const LAY_DANH_SACH_NGUOI_DUNG = "LAY_DANH_SACH_NGUOI_DUNG";

export const LAY_DANH_SACH_NGUOI_DUNG_KEYWORD =
  "LAY_DANH_SACH_NGUOI_DUNG_KEYWORD";

export const LAY_DANH_SACH_LOAI_NGUOI_DUNG = "LAY_DANH_SACH_LOAI_NGUOI_DUNG";

export const LAY_DS_HTR = "LAY_DS_HTR";
export const LAY_DS_CR = "LAY_DS_CR";
